# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: U.S. Senator Barbara Boxer
description: Official Website of United States Senator Barbara Boxer, of California
author:
  name: Joaquin Esquivel, Tom Standifer
  email: Joaquin_Esquivel@boxer.senate.gov, Tom_Standifer@boxer.senate.gov

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

permalink: none
paginate: 0
paginate_path: 'page:num'

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

pygments: false
